PUT http://app:8080/api/users/1
Content-Type: application/json

{
    "id":1,
    "name": "Thierry",
    "password": "HelloHello1@",
    "role": "ADMIN",
    "mail": "ttot@gmail.com",
    "pokemonsCatching": null
}