server:
  port: 8080
spring:
  main:
    web-application-type: servlet
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_ID_KEY}
            client-secret: ${GITHUB_SECRET_KEY}
            scope: profile, email
            redirect-uri: "https://tfe.unthier.ip-ddns.com/api/login/oauth2/code/github"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user