POST http://app:8080/api/trainersPokemons
Content-Type: application/json

{
    "name": "Bulbasaur",
    "pokemonId": 1,
    "attack": 49,
    "speed": 45,
    "pv": 45,
    "defense": 49,
    "level": 4,
    "captureRate": 45,
    "type": "GRASS",
    "trainer": {
        "id": 1
    },
    "damage": 0
}

# {
#     "name": "Bulbasaur",
#     "attack": 49,
#     "speed": 45,
#     "pv": 45,
#     "defense": 49,
#     "captureRate": 45,
#     "type": "GRASS",
#     "nextEvolutionLevel": 16,
#     "nameOfNextEvolution": "Ivysaur"
# }